### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by muzena** [vzamanillo/desktop#10]
@vzamanillo 
In settings:
When I try change settings it opens Terminal and ask me password 
Eg. subtitle language can't change subs size

In movie missing google cloud
In develop version google cloud in TV shows works unlike in master branch version and thumbnails are available
Build don't work
Some message about missing clean file

**Comment by vzamanillo** [comment]
@muzena , Hi!! the terminal bug is confirmed, I am doing some tests to fix it, I will check the rest later to fix it.

Thank you for reporting!!

**Comment by muzena** [comment]
@vzamanillo 
In TV shows, wont start playing, then i open in external player and it work, stop external player, start back PC player and then work.

**Comment by muzena** [comment]
@vzamanillo 
Start PT it ask you DEFAULT TOREN...
select Yes It starts Terminal and ask admin rights.

**Comment by vzamanillo** [comment]
Thats right, needs priviliges to reg PCTCE as default torrent client

**Comment by muzena** [comment]
@vzamanillo 
How to generate msi install file win64/32 in linux?
Can you made some script for that, i watch in /butter/dist/ scripts but i don't understand it.

**Comment by vzamanillo** [comment]
I have not the installer script for Windows yet, but you can build and package your application using the gulp task `build`
