### ISSUE TITLE
TV shows wont start playing

### ISSUE THREAD

**Issue by vzamanillo** [vzamanillo/desktop#13]
In TV shows, wont start playing, then i open in external player and it work, stop external player, start back PC player and then work.

**Comment by vzamanillo** [comment]
Need more info about the steps to reproduce the issue, could you please give me more details?

**Comment by muzena** [comment]
@vzamanillo 
Now i try again, now work but it need to wait about 10 sec to start play video after starting PT player.

**Comment by vzamanillo** [comment]
Ok, closing, tell me if it is neccesary to reopen it in the future, if it happens again.
