### ISSUE TITLE
Streaming to Samsung TV does not work

### ISSUE THREAD

**Issue by vzamanillo** [vzamanillo/desktop#14]
I try to stream to Samsung tv. Same movie same format 1080 resolution don't work in TV message that file type is not supported, but in 720 resolution work, first time run it starts about 10 sec then stop, then run again and work, but subtitles missing.

**Comment by muzena** [comment]
@vzamanillo 
This sometimes start playing on 1080, sometimes not.

**Comment by vzamanillo** [comment]
Could you please send me a screenshot of the dev console while is playing?

**Comment by muzena** [comment]
@vzamanillo 
Can you tell me which port do I open in firewall to DLNA work, it works only when firewall disabled.
Screenshot:
![strea](https://cloud.githubusercontent.com/assets/1978777/16623210/515841ec-439d-11e6-8203-039bed0833e2.png)

**Comment by vzamanillo** [comment]
@muzena , thank you for the screenshot, about DLNA tcp port, try opening `9999`.

**Comment by vzamanillo** [comment]
@muzena, maybe the problem with the subtitiles when you are playin externally is related to a tcp port filtering in your machine, the subtitles are server in the 9999 tcp port, could you please tray to stream to Samsung TV with the firewall disabled?

**Comment by muzena** [comment]
@vzamanillo 
No, I try streaming with disabled firewall, only that works.
I try open port 9999 but don't work, and other port from google search and these from samsung: https://forum.samygo.tv/viewtopic.php?t=4521
Once, i sucessfuly open ports but i don't remember anymore these numbers of ports. 

In old popcorn time app subtitles are worked over DLNA.
