### ISSUE TITLE
AC3 encoded multimedia plays video only, no audio

### ISSUE THREAD

**Issue by vzamanillo** [vzamanillo/desktop#5]
The default prebuilt of the ffmpeg codec does not support AC3 audio because the proprietary is Dolby and is not Open Source so Chromium does not include it.

Steps to reproduce:

The 720p Tv Shows audio are usually encoded with AC3, try to play some of them.

It would be nice to migrate to webchimera or another more complete player.

**Comment by ajkblue** [comment]
What is the reason that this works in the original PopcornTime codebase that this is forked off of and not your version?

**Comment by vzamanillo** [comment]
Hi, 

the original codebase uses a custom pre-compiled Nw.js version with proprietary codecs, the official version uses a default chromium whos not include that codecs because can not distributed due licensig reasons.

**Comment by vzamanillo** [comment]
I am working on it right now, interesting information about how to compile ffmpeg with proprietary codecs

https://github.com/butterproject/butter-desktop/issues/339#issuecomment-203683778
https://github.com/nwjs/nw.js/issues/1461
https://github.com/kjthegod/ffmpeg/compare/b9d631d0ad277109678e86d729acc889793b4b94...master

Needs to be reviewed because is pretty old, but is a good point to start.

**Comment by vzamanillo** [comment]
For now we can build ffmpeg with proprietary codecs (aac,h264,mp3,mpeg4,hevc,ac3,aac3,mpegvideo,msmpeg4v1,msmpeg4v2,msmpeg4v3,flv,dca and flac) with my fork of [nwjs-ffmpeg-prebuilt](https://github.com/vzamanillo/nwjs-ffmpeg-prebuilt), but bad news... the prebuilt NW.js packages does not have the interface to proprietary codecs (proprietary_codecs=true) so we need both custom builds to get it working, one for ffmpeg with the proprietary codecs and the other one for NW.js with the needed interface for them, I am working in a new script to do that.

**Comment by ajkblue** [comment]
Sweet! I hope this will work since many tv shows audio are encoded in this format.

**Comment by vzamanillo** [comment]
Finally we have AC3 audio , but, this repository will be dead soon, I am trying to collaborate with the official butter and popcorntime projects helping to migrate to nw.js > 0.13, keep an eye on both.

**Comment by ajkblue** [comment]
@vzamanillo Why will this repo be dead soon? Are you going to close down your fork?

**Comment by ajkblue** [comment]
And I don't see that AC3 audio is working after compiling

**Comment by vzamanillo** [comment]
I am trying to collaborate with the official butter and popcorntime projects, a good community with a good attitude, the codebase of this fork is not a real community, It was not a good choice forking from them, dirty code... etc, Butter and official PCT are ahead.

About the FFmpeg library, you can build your own with proprietary codecs with the prebuild script from [iteufel](https://github.com/iteufel/nwjs-ffmpeg-prebuilt), you have not to do something special to compile it on Mac or Linux, was tested on all platforms.
